- name: "Capturing EOS Facts with Conditions"
  hosts: eos-switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Capture facts from EOS device
      eos_facts:
      register: eosfacts_out

    - name: Uing lineinfile to print ansible_net_hostname to file using "when" Conditional ansible_net_model == "vEOS"
      lineinfile:
        dest: ./out/lineinfo.txt
        line: "{{ansible_net_hostname}} is running vEOS"
        state: present
        create: yes
      when: ansible_net_model == "vEOS"

    - name: Using blockinfile to insert multiple lines
      blockinfile:
        dest: ./out/blockfile.txt
        create: yes
        block: |
          "{{ansible_net_hostname}}, {{ansible_net_interfaces.Management1.ipv4.address}} is running vEOS"
          "{{ansible_net_hostname}} is running {{ansible_net_version}}"
      when: ansible_net_model == "vEOS"

#https://www.netnea.com/cms/2016/10/16/using-ansible-to-fetch-information-from-ios-devices/
