- name: "Demonstrate connecting to switches"
  hosts: eos-switches
  gather_facts: yes

  tasks:
    ###
    # Collect data
    #
    - name: Gather facts (eos)
      eos_facts:
#      become: yes
#      become_method: enable
      when: ansible_network_os == 'eos'

    ###
    # Demonstrate variables
    #
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Facts from a specific host
      debug:
        var: hostvars['eos.test']

    - name: Write facts to disk using a template
      copy:
        content: |
          #jinja2: lstrip_blocks: True
          EOS device info:
            {% for host in groups['eos'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}

    ###
    # Get running configuration
    #

    - name: Backup switch (eos)
      eos_config:
        backup: yes
      register: backup_eos_location
      when: ansible_network_os == 'eos'

    - name: Create backup dir
      file:
        path: "./backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes

#    - name: Copy backup files into ./backups/ (eos)
#      copy:
#        src: "{{ backup_eos_location.backup_path }}"
#        dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
#      when: ansible_network_os == 'eos'
