- name: "Demonstrate connecting to switches"
  hosts: ios-switches
  gather_facts: yes
  connection: network_cli
  tasks:
    - name: Showing version of Switch (ios)
      ios_command:
        commands: show version
    - name: Change Host name
      ios_config:
        lines:
          - hostname hostname
    - name: Add Vlans to Switch
      ios_vlan:
        state: active
        purge: yes
        aggregate:
          - { vlan_id: 1, name: default }
          - { vlan_id: 2, name: Vlan_2 }
          - { vlan_id: 3, state: suspend }
          - { vlan_id: 4000, name: new_vlan }
          - { vlan_id: 250, name: vlan_250 }
          - { vlan_id: 500, name: vlan_500 }
          - { vlan_id: 51, name: vlan_50 }
