- name: "Connecting to switches: capture Vlans, save running conf, and backup conf"
  hosts: switches
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Showing vlan of Switch (eos)
      eos_command:
        commands: show vlan brief
      when: ansible_network_os == 'eos'
      register: show_vlan
    - name: Showing vlan of Switch (ios)
      ios_command:
        commands: show vlan brief
      when: ansible_network_os == 'ios'
      register: show_vlan
    - name: save running to startup when modified
      eos_config:
        save_when: modified
      when: ansible_network_os == 'eos'
    - name: Backup current switch config (eos)
      eos_config:
        backup: yes
      when: ansible_network_os == 'eos'
      register: eos_backup

    - copy: content="{{ show_vlan.stdout[0] | parse_cli('./filter/vlan.yaml') }}" dest="out/{{inventory_hostname}}_vlan.json"
#https://www.netnea.com/cms/2016/10/16/using-ansible-to-fetch-information-from-ios-devices/
